### ISSUE TITLE
add support for .gz files

### ISSUE THREAD

**Issue by seanbreckenridge** [karlicoss/kompress#1]
In other words if you have a file like:

```
touch test.json
```

I often run something like
```
gzip --best test.json

# gunzip test.json.gz to reverse
```

to compress it

dont think there would be any complications with adding, will make a PR

**Comment by karlicoss** [comment]
ah cool! I'm usually using `zstd -19 --quiet -o /dev/stdout` -- seems like the best compression ratio and pretty fast. But makes sense to have gz support too
